# Generated by Django 6.0.3 on 2026-03-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('shipped', 'Отправлен'), ('completed', 'Завершён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
